### ISSUE TITLE
`podman-hpc migrate` Permission denied 

### ISSUE THREAD

**Issue by wahabk** [NERSC/podman-hpc#116]
Hello, we have been using `podman-hpc` on our Cray EX system Isambard-AI with great success and are big fans.

We have a slightly different setup since our [compute nodes don't have storage but our login-nodes do](https://docs.isambard.ac.uk/user-documentation/information/system-storage/).

When I try to migrate this image from this directory to $SCRATCH:

```
$ podman-hpc migrate IMAGE
Permission denied: '/local/user/<user-id>/storage/overlay/6f3206c08a5a2994bd7662047df98e0f934f520860694dc9d9252691ab9cea59/link'
```

So we had to get an admin to `rm -rf /local/user/1483800130/storage/overlay`, we then run (as a user) `podman-hpc system reset && podman-hpc system migrate`.

Then re-pull the container. Only for migrate to raise:

```
No such file or directory: '/local/user/<user-id>/storage/overlay/6f3206c08a5a2994bd7662047df98e0f934f520860694dc9d9252691ab9cea59/link'
```

I tried all the following https://docs.nersc.gov/development/containers/podman-hpc/overview/#troubleshooting Including removing `~/.local/share/containers`. 

Do you know how can I remove the need for that overlay hash link and reset the podman config?

**Comment by wahabk** [comment]
Full stack trace from pulling an NGC container:

```
INFO: Migrating image to /scratch/brics/akawafi1.brics/storage
Traceback (most recent call last):
  File "/usr/bin/podman-hpc", line 11, in <module>
    load_entry_point('podman-hpc==1.1.0', 'console_scripts', 'podman-hpc')()
  File "/usr/lib/python3.6/site-packages/podman_hpc/podman_hpc.py", line 441, in main
    podhpc(prog_name="podman-hpc")
  File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/podman_hpc/podman_hpc.py", line 206, in pull
    mu.migrate_image(image)
  File "/usr/lib/python3.6/site-packages/podman_hpc/migrate2scratch.py", line 460, in migrate_image
    self._copy_overlay(img_id, rld)
  File "/usr/lib/python3.6/site-packages/podman_hpc/migrate2scratch.py", line 363, in _copy_overlay
    copy(src, dst)
  File "/usr/lib64/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/local/user/1483800130/storage/overlay/6f3206c08a5a2994bd7662047df98e0f934f520860694dc9d9252691ab9cea59/link'
```

**Comment by wahabk** [comment]
Friendly ping to see if someone is available to take a look at this? Thank you.

**Comment by danfulton** [comment]
Is it possible the files were owned by your own subordinate ids (listed in `/etc/subuid`)?  If so, you may be able to clean them up be entering into a namespace outside of a container by using user namespace share `unshare`.  

Another option which is somewhat nuclear is `podman system reset`.  This will clear your storage though, so make sure you have pushed up an irreproducible containers to a registry first.

**Comment by wahabk** [comment]
Thank you for your reply @danfulton. So you are correct the issue was the subids at the beginning. After nuking everything there was still a reference to the old layer hash and I would get `No such file or directory`.

After doing some grepping with the hash I was able to find the culprits:

```
$SCRATCHDIR/storage/overlay-images/images.json
$SCRATCHDIR/storage/overlay-layers/layers.json
```

After removing these, starting a new terminal, and `podman-hpc system migrate` it works for me. This was a vestigial remain after `system reset`.

However, I was able to replicate the error:

```
$ podman-hpc migrate nvcr.io/nvidia/pytorch:24.04-py3
PermissionError: [Errno 13] Permission denied: '$TMPDIR/storage/overlay/2cd5fd9333fe450314639c7104a5cf71a7b8db95c7ac922ae518353bd4c0cc34/link'
$ ls -l /local/user/1483800130/storage/overlay/
drwx------ 5     2154168320     2154168320  4096 Sep 26 16:04 2cd5fd9333fe450314639c7104a5cf71a7b8db95c7ac922ae518353bd4c0cc34
drwx------ 5     2154168320     2154168320  4096 Sep 26 16:02 8efb35e1b6a92d1e93a2a92bd39fe7122e97dee738251d3c39155613316222f3
[redacted overlays owned by me]
```

I believe this is an issue with NGC containers. 2 of the overlays/layers have the subordinate ids and are not owned by me. Can you think of a workaround/solution for this? I will give the namespace trick a go.

**Comment by wahabk** [comment]
Okay I found the issue. This arises after running an image with `--openmpi-pmix` and does not have to do with migrating the image.

```
$ podman-hpc pull nvcr.io/nvidia/cuda:12.6.1-cudnn-runtime-ubuntu20.04
$ podman-hpc images
REPOSITORY           TAG                               IMAGE ID      CREATED      SIZE        R/O
nvcr.io/nvidia/cuda  12.6.1-cudnn-runtime-ubuntu20.04  660e34b71eac  3 weeks ago  3.13 GB     false
nvcr.io/nvidia/cuda  12.6.1-cudnn-runtime-ubuntu20.04  660e34b71eac  3 weeks ago  3.13 GB     true
$ podman-hpc run --rm --gpu nvcr.io/nvidia/cuda:12.6.1-cudnn-runtime-ubuntu20.04 nvidia-smi --list-gpus
[Correct output...]
$ ls -l /local/user/1483800130/storage/overlay
total 56
...
drwx------ 5 me me  4096 Sep 27 15:06 f6529d421363090400177a325e3bdb2db972fd9efd98b2213537de1d571bb3be
drwxr-xr-x 2 me me 12288 Sep 30 09:09 l
```

But when I run it with `--openmpi-pmix`, I find a new file in my `$LOCALDIR/overlay` that is owned by my subordinate uid `1`:

```
$ podman-hpc run --rm --gpu-trial --openmpi-pmix nvcr.io/nvidia/cuda:12.6.1-cudnn-runtime-ubuntu20.04 nvidia-smi --list-gpus
Error: runc: runc create failed: unable to start container process: error during container init: error creating device nodes: open /local/user/1483800130/storage/overlay/bfae73e87ffbb5224576b3f365cd9d7cce9f812d668f8dd6d1250c579a31cebe/merged/dev/dri/card0: permission denied: OCI permission denied
$ ls -l /local/user/1483800130/storage/overlay
total 60
...
drwx------ 5 me me  4096 Sep 27 15:11 e75e62e2e5c443d58aff06b60c422792543471f2ebc40d133800b7db26ee9c53
drwx------ 5     2154168320     2154168320  4096 Sep 30 09:09 ec0a27ecdd20da299f2f3cdb0fd8a96713d4ca543f09003cc69162d536251543
drwx------ 5 me me  4096 Sep 27 15:06 f6529d421363090400177a325e3bdb2db972fd9efd98b2213537de1d571bb3be
drwxr-xr-x 2 me me 12288 Sep 30 09:09 l
```

**Comment by wahabk** [comment]
@danfulton I will do more testing on whether this is caused by `--userns-keep-id` or `--privileged` etc. Let me know if you have any advice on how to counter this and whether you have faced it before.

**Comment by danfulton** [comment]
I believe `--userns=keep-id` will do some chown operations which can cause issues like this, and generally I try to avoid it.  It is less convenient, but I think the best practice is to have a service/application user in your image, and then [manually specify uid and gid maps](https://docs.podman.io/en/v5.2.2/markdown/podman-run.1.html#uidmap-flags-container-uid-from-uid-amount).  There are some caveats if you are mounting shared datasets into your container though.

We have been kicking around the idea of providing helpers for some common map patterns for HPC users, but we don't have them at present.

**Comment by wahabk** [comment]
Thanks Dan. I've tried to work around `--userns=keep-id` by manually mapping the uids and gids with no success. It's quite tricky since our user access nodes and compute nodes have 2 different file systems. `--userns=keep-id` makes my containers take 3 minutes (!!) to launch. For now I have podman containers using Slingshot through libfabric with good OSU latency and NCCL bandwidth.

The only reason I need to `keep-id` is that I get this error when running MPI without it:

```
: [23765.0]: pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
```

If you have any recommendations/workarounds please let me know. Otherwise I think I've documented this issue and it's workarounds so feel free to close the issue. Thanks again.
