### ISSUE TITLE
`$PYTHONPATH` can cause `podman-hpc` fail to load yaml module

### ISSUE THREAD

**Issue by wholtz** [NERSC/podman-hpc#78]
```
wjholtz@login30:~/jamo-report$ PYTHONPATH='' podman-hpc version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.17.13
Built:        Tue Nov 22 04:00:00 2022
OS/Arch:      linux/amd64
wjholtz@login30:~/jamo-report$ PYTHONPATH=/global/common/software/nersc/pm-2022q3/jamo/prod/lib/python podman-hpc version
Traceback (most recent call last):
  File "/usr/bin/podman-hpc", line 11, in <module>
    load_entry_point('podman-hpc==1.0.2', 'console_scripts', 'podman-hpc')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/podman_hpc/podman_hpc.py", line 12, in <module>
    from .siteconfig import SiteConfig
  File "/usr/lib/python3.6/site-packages/podman_hpc/siteconfig.py", line 7, in <module>
    from yaml import FullLoader
ImportError: cannot import name 'FullLoader'
wjholtz@login30:~/jamo-report$ 
```

**Comment by lastephey** [comment]
This is difficult to address since podman-hpc needs Python, and will be sensitive to various user-defined settings. For now I think we can list this as a known issue.

**Comment by lastephey** [comment]
We now mention this is in the `known issues` part of our docs page. 

https://gitlab.com/NERSC/nersc.gitlab.io/-/merge_requests/2469

I think this is sufficient for now, so I'll go ahead and close.
